### ISSUE TITLE
Provide ability for teams to manage their recurring events

### ISSUE THREAD

**Issue by cassidyjames** [GetTogetherComm/GetTogether#139]
I created a weekly recurring event at https://gettogether.community/events/271/thursday-co-working/

However, it appears it is going to repeat in perpetuity now, as editing that event to remove the weekly occurrence does not work, nor does editing the latest event in the series: https://gettogether.community/events/508/thursday-co-working/

**Comment by mhall119** [comment]
Changing it to remove the association with the weekly occurrence is easy, but what's the logical thing to happen then? Options are:

1. Delete the Series object. No new events will be created, and old events will lose their recurrence information (but no other information). From a code standpoint this is the simplest and cleanest.

2. Update the Series object to add an "end date" for recurrences set to the date you unset it from an event. No new events will be created, and old events will still show their old recurrence data.

If 2, should the Series be locked so that you can't edit it at all? It wouldn't make sense to edit it, I would think, but this means you wouldn't be able to undo this change once it happens, you'd have to create a new Series for recurrences.

**Comment by cassidyjames** [comment]
I didn't realize there was an editable series object at all! So I went ahead and deleted the recurring one and can do that in the future if need be. Being able to edit to set an end date still seems useful, but at least being able to delete the series works for now.

**Comment by mhall119** [comment]
@cassidyjames does the new "Recurring events" listing on a team's event page make it easier to edit/delete recurring events? If so, can we close this issue?

**Comment by cassidyjames** [comment]
@mhall119 lgtm
