### ISSUE TITLE
Convert between local time on the user-facing screens and UTC for storage in the database

### ISSUE THREAD

**Issue by mhall119** [GetTogetherComm/GetTogether#59]
Right now GetTogether is kind of timezone-ignorant. Everything is handled in UTC, but the interface makes you think it's in local time. Need to:
* [ ] Convert times from local (to the user, team or event) to UTC when saving data
* [ ] Convert from UTC to local (to the user, team or event) when displaying data
* [ ] Try to auto-assign timezones for for users, teams or events based on other data (location, geoip, etc)

**Comment by deutrino** [comment]
Hey there. I worked on refactoring a highly complicated calendaring system over a period of more than a year because of bugs related to storing time in UTC. They often manifested as daylight savings / summer time bugs appearing on recurring events, but the fail went very very deep and was a major source of headaches for a long time. Since you're building anew here, you can avoid this from the start.

Storing times as UTC *will* end in blood and tears and potentially a long refactoring later. This is especially important for recurring event series. 

You want to store the times as "intended time" (my name for it): a combination of the time *and time zone* for when the event is to occur. Then, when displaying the event, query it using the Olson tzinfo database with the time zone in which the event is to be displayed, which will do any necessary conversions for you.

This becomes necessary for e.g. users in countries with differing definitions of daylight savings time, or for when laws about daylight savings are changed in a country with ongoing recurring events, etc. It is even relevant solely within the United States, where some areas do not observe DST; further, the EU is again toying with the idea of ending summer time, and Russia made changes in recent years.

**Comment by deutrino** [comment]
See also https://www.w3.org/TR/timezone/

Thanks to @georgedorn for tipping me off to this ticket.

**Comment by mhall119** [comment]
Wow, thanks for the advice @deutrino! I've always stored datetimes in UTC, but none of those projects ever had to deal with recurring events, I can see how that would lead to undesirable outcomes.

**Comment by mhall119** [comment]
For now I've updated everything to store as UTC. Since we have the timezone we can always get back to "intended time" when we need it. When I start on recurring events, that data might be stored in "intended time" rather than UTC to avoid that extra step.
